In [1]:
import pandas as pd
import numpy as np
import json
import os

#Load Dataset

In [2]:
DATA_PATH = "../data/raw/airbnb.csv"

df = pd.read_csv(DATA_PATH)

df.head()

,id,host id,host_identity_verified,neighbourhood group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room type,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,80014485718,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,United States,False,strict,Private room,966.0,193.0,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0
1,1002102,52335172823,verified,Manhattan,Midtown,40.75362,-73.98377,United States,False,moderate,Entire home/apt,142.0,28.0,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0
2,1002403,78829239556,NaN,Manhattan,Harlem,40.80902,-73.94190,United States,True,flexible,Private room,620.0,124.0,3.0,0.0,NaN,0.00,5.0,1.0,352.0
3,1002755,85098326012,unconfirmed,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,True,moderate,Entire home/apt,368.0,74.0,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0
4,1003689,92037596077,verified,Manhattan,East Harlem,40.79851,-73.94399,United States,False,moderate,Entire home/apt,204.0,41.0,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0

#Shape

In [3]:
rows, cols = df.shape

print(f"Rows: {rows}")
print(f"Columns: {cols}")

df.columns.tolist()

Rows: 98970
Columns: 20

['id',
 'host id',
 'host_identity_verified',
 'neighbourhood group',
 'neighbourhood',
 'lat',
 'long',
 'country',
 'instant_bookable',
 'cancellation_policy',
 'room type',
 'price',
 'service fee',
 'minimum nights',
 'number of reviews',
 'last review',
 'reviews per month',
 'review rate number',
 'calculated host listings count',
 'availability 365']

#Missing Value Percentage

In [4]:
missing = df.isnull().sum()
missing_percent = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_percent
}).sort_values(by="missing_percent", ascending=False)

missing_df

                                missing_count  missing_percent
last review                             15030        15.186420
country                                   513         0.518339
minimum nights                            365         0.368799
review rate number                        297         0.300091
calculated host listings count            290         0.293018
host_identity_verified                    268         0.270789
neighbourhood                              13         0.013135
lat                                         8         0.008083
long                                        8         0.008083
neighbourhood group                         0         0.000000
id                                          0         0.000000
host id                                     0         0.000000
price                                       0         0.000000
room type                                   0         0.000000
cancellation_policy                         0         0.000000
instant_bookable                            0         0.000000
number of reviews                           0         0.000000
service fee                                 0         0.000000
reviews per month                           0         0.000000
availability 365                            0         0.000000

#Unique Values

In [5]:
categorical_cols = df.select_dtypes(include=["object"]).columns

unique_summary = {}

for col in categorical_cols:
    unique_summary[col] = df[col].nunique()

pd.DataFrame.from_dict(unique_summary, orient='index', columns=["unique_count"])

                        unique_count
host_identity_verified             2
neighbourhood group                7
neighbourhood                    224
country                            1
cancellation_policy                3
room type                          4
last review                     2445

#Basic Statistics

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,98970.0,2.974592e+07,1.598394e+07,1.001254e+06,1.617371e+07,2.987475e+07,4.344490e+07,5.736742e+07
host id,98970.0,4.923761e+10,2.854432e+10,1.236005e+08,2.455960e+10,4.910045e+10,7.396781e+10,9.876313e+10
lat,98962.0,4.072798e+01,5.596694e-02,4.049979e+01,4.068869e+01,4.072217e+01,4.076267e+01,4.091697e+01
long,98962.0,-7.394935e+01,4.988365e-02,-7.424984e+01,-7.398253e+01,-7.395432e+01,-7.393193e+01,-7.370522e+01
price,98970.0,6.257374e+02,3.313518e+02,5.000000e+01,3.410000e+02,6.240000e+02,9.130000e+02,1.200000e+03
service fee,98970.0,1.251195e+02,6.625394e+01,1.000000e+01,6.800000e+01,1.250000e+02,1.830000e+02,2.400000e+02
minimum nights,98605.0,8.135855e+00,2.889590e+01,-1.223000e+03,2.000000e+00,3.000000e+00,5.000000e+00,5.645000e+03
number of reviews,98970.0,2.714920e+01,4.892850e+01,0.000000e+00,1.000000e+00,7.000000e+00,3.000000e+01,1.024000e+03
reviews per month,98970.0,1.178189e+00,1.693001e+00,0.000000e+00,9.000000e-02,4.900000e-01,1.740000e+00,9.000000e+01
review rate number,98673.0,3.286715e+00,1.279205e+00,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00
calculated host listings count,98680.0,8.060661e+00,3.265645e+01,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,3.320000e+02
availability 365,98970.0,1.346621e+02,1.298415e+02,0.000000e+00,2.000000e+00,9.000000e+01,2.540000e+02,3.660000e+02

In [7]:
df.median(numeric_only=True)

id                                2.987475e+07
host id                           4.910045e+10
lat                               4.072217e+01
long                             -7.395432e+01
instant_bookable                  0.000000e+00
price                             6.240000e+02
service fee                       1.250000e+02
minimum nights                    3.000000e+00
number of reviews                 7.000000e+00
reviews per month                 4.900000e-01
review rate number                3.000000e+00
calculated host listings count    1.000000e+00
availability 365                  9.000000e+01
dtype: float64